# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jarvis < Formula
  desc "Onchain (EVM compatible) operation made easy"
  homepage "https://github.com/tranvictor/jarvis"
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/tranvictor/jarvis/releases/download/v0.2.2/jarvis_0.2.2_macOS_amd64.tar.gz"
      sha256 "9111d8e3956b190fae547518853b6bacfaecdc2ab0065ebd774b0c2eb803e361"

      def install
        system "make", "jarvis" if build.head?
        bin.install "bin/jarvis"
      end
    end
    on_arm do
      url "https://github.com/tranvictor/jarvis/releases/download/v0.2.2/jarvis_0.2.2_macOS_arm64.tar.gz"
      sha256 "9c99b3303d6c9b2608063b73a2c4e1e27e6b52eee3ec40373ed95fdc01e8849b"

      def install
        system "make", "jarvis" if build.head?
        bin.install "bin/jarvis"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tranvictor/jarvis/releases/download/v0.2.2/jarvis_0.2.2_linux_amd64.tar.gz"
        sha256 "f9a15738acd9149586279109816d8138e475a6813c40193f6e64066dd4533ba5"

        def install
          system "make", "jarvis" if build.head?
          bin.install "bin/jarvis"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tranvictor/jarvis/releases/download/v0.2.2/jarvis_0.2.2_linux_arm64.tar.gz"
        sha256 "afb4a170964eccf0e9e6f9b2e1adf0e0dc5d32c12f9e71454c29322e99ec4f7a"

        def install
          system "make", "jarvis" if build.head?
          bin.install "bin/jarvis"
        end
      end
    end
  end

  head do
    url "https://github.com/tranvictor/jarvis.git"
    depends_on "go"
  end

  def caveats
    <<~EOS
      After a new GitHub release, refresh the tap before upgrading:
        brew update
        brew upgrade tranvictor/jarvis/jarvis
    EOS
  end

  test do
    help_text = shell_output("jarvis -h")
    assert_includes help_text, "Usage:"
  end
end
