# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jarvis < Formula
  desc "Onchain (EVM compatible) operation made easy"
  homepage "https://github.com/tranvictor/jarvis"
  version "0.0.24"

  on_macos do
    url "https://github.com/tranvictor/jarvis/releases/download/v0.0.24/jarvis_0.0.24_macOS_amd64.tar.gz"
    sha256 "ef12c8f98c9d24b34b9cc0590513cbfcc4f251471715d7c0629a1fba8f5c0f06"

    def install
      system "make", "jarvis" if build.head?
      bin.install "bin/jarvis"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Jarvis
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tranvictor/jarvis/releases/download/v0.0.24/jarvis_0.0.24_linux_arm64.tar.gz"
      sha256 "d604a75dbe0c56ee309ac0558c9751ede07a652254af0ad3ffb6f95fd6864c41"

      def install
        system "make", "jarvis" if build.head?
        bin.install "bin/jarvis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tranvictor/jarvis/releases/download/v0.0.24/jarvis_0.0.24_linux_amd64.tar.gz"
      sha256 "cfa0c0d66a70ebbe862733b347e0a47ddfaec4c2c8fd1e6dc218512477a7ceef"

      def install
        system "make", "jarvis" if build.head?
        bin.install "bin/jarvis"
      end
    end
  end

  head do
    url "https://github.com/tranvictor/jarvis.git"
    depends_on "go"
  end

  test do
    help_text = shell_output("jarvis -h")
    assert_includes help_text, "Usage:"
  end
end
